"""Synthetic oral epithelium with planted ground truth.

Shared by the demo and by the Calibration Range, so that the thing being measured
and the thing being demonstrated are generated by exactly the same code.

Everything is parameterised so a cohort can be generated with a phenomenon present
at a chosen strength, or absent entirely (a pure-null cohort), with artefacts
switched on and off independently.
"""
from __future__ import annotations

import math
import random
from dataclasses import dataclass

from .fields import FeatureField

PHI = [0.05 + 0.9 * i / 19 for i in range(20)]
SIGMA_LOG = 0.05


@dataclass
class CohortSpec:
    n_specimens: int = 80
    #: coupling between the nc_ratio and chromatin decay rates. 1.0 = the invariant
    #: holds exactly, 0.0 = they decay independently and there is nothing to find.
    coupling: float = 1.0
    #: coupling between nc_ratio and nuclear_area. Realistically 1.0 (they genuinely
    #: co-vary); set to 0.0 to build a cohort with NO invariant anywhere, which is what
    #: a pure-null calibration run needs.
    area_coupling: float = 1.0
    #: nuclear_area duplicates nc_ratio off the same mask -> manufactured invariant
    inject_shared_mask: bool = True
    #: scanner steepens the orientation gradient, and scanner correlates with condition
    inject_scanner_confound: bool = True
    #: multiplicative scanner gain on chromatin (a benign, constant, level-only effect)
    inject_chromatin_gain: bool = True
    p_scanner_b_given_dysplasia: float = 0.8
    p_scanner_b_given_normal: float = 0.2
    seed: int = 20260903


def generate(spec: CohortSpec) -> tuple[dict, dict, dict]:
    """Return (fields_by_specimen, labels, strata)."""
    rng = random.Random(spec.seed)
    fields_by_specimen, labels, strata = {}, {}, {}

    for i in range(spec.n_specimens):
        sid = f"S{i:03d}"
        condition = "dysplasia" if rng.random() < 0.5 else "normal"
        p_b = (spec.p_scanner_b_given_dysplasia if condition == "dysplasia"
               else spec.p_scanner_b_given_normal)
        scanner = "B" if rng.random() < p_b else "A"
        stain_lot = rng.choice(["L1", "L2"])
        stratum = {"scanner": scanner, "stain_lot": stain_lot, "lab": "central"}

        k = rng.uniform(1.2, 3.0)              # differentiation rate for nc_ratio
        k_b = spec.coupling * k + (1.0 - spec.coupling) * rng.uniform(1.2, 3.0)
        k_area = spec.area_coupling * k + (1.0 - spec.area_coupling) * rng.uniform(1.2, 3.0)
        a = rng.uniform(0.5, 1.5)
        b = rng.uniform(0.8, 2.4)
        d = rng.uniform(6.0, 11.0)
        o = rng.uniform(0.30, 0.45)

        chrom_gain = 1.15 if (scanner == "B" and spec.inject_chromatin_gain) else 1.0
        lot_curv = 0.35 if stain_lot == "L2" else 0.0
        orient_slope = 0.10 + (0.25 if (scanner == "B" and spec.inject_scanner_confound)
                               else 0.0)

        nc, chrom, area, nbr, orient = [], [], [], [], []
        for phi in PHI:
            shared_err = rng.gauss(0.0, SIGMA_LOG)      # same mask -> same error
            lot_term = lot_curv * (phi - 0.5) ** 2
            nc.append(a * math.exp(-k * phi) * math.exp(shared_err + lot_term))
            if spec.inject_shared_mask:
                area.append(1.9 * a * math.exp(-k_area * phi)
                            * math.exp(shared_err + lot_term + rng.gauss(0, 0.01)))
            else:
                area.append(1.9 * a * math.exp(-k_area * phi)
                            * math.exp(lot_term + rng.gauss(0, SIGMA_LOG)))
            chrom.append(b * chrom_gain * math.exp(-k_b * phi)
                         * math.exp(rng.gauss(0, SIGMA_LOG)))
            nbr.append(d * (1 + 0.6 * phi) * math.exp(rng.gauss(0, SIGMA_LOG)))
            orient.append((o + orient_slope * phi) * math.exp(rng.gauss(0, 0.03)))

        def mk(q, vals, mask, sig=SIGMA_LOG):
            return FeatureField(q, sid, PHI, vals, sig, mask, stratum)

        fields_by_specimen[sid] = {
            "nc_ratio": mk("nc_ratio", nc, "seg_v3_nuc_cyto"),
            "nuclear_area": mk("nuclear_area", area,
                               "seg_v3_nuc_cyto" if spec.inject_shared_mask else "seg_v4_area"),
            "chromatin": mk("chromatin", chrom, "texture_v2"),
            "neighbour_dist": mk("neighbour_dist", nbr, "seg_v3_centroids"),
            "orient_coherence": mk("orient_coherence", orient, "orient_v1", 0.03),
        }
        labels[sid] = condition
        strata[sid] = stratum
    return fields_by_specimen, labels, strata


#: The candidate the generator actually plants, when coupling > 0.
TRUE_INVARIANT_COMPONENTS = frozenset({"nc_ratio", "chromatin"})
